[package]
name = "todo-actixweb"
version = "0.1.0"
authors = ["sunakan <sunakan03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
